# From https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
version: '3.5'
services:
  nginx:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./conf/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    logging:
      options:
        max-size: "1m"
    restart: always
    networks:
      - default
      - nginx-proxy2

networks:
  default:
    external:
      name: nginx-proxy
  nginx-proxy2: 
    external: 
      name: nginx-proxy2
